# CI workflow 

name: CI

on:
    workflow_dispatch:
    pull_request:
      types: [ assigned, opened, synchronize, reopened ]
    push:
      branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet-version: [ 5, 6, 7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install PDK
        run: |
          wget https://apt.puppet.com/puppet-tools-release-focal.deb
          sudo dpkg -i puppet-tools-release-focal.deb
          sudo apt-get update
          sudo apt-get install pdk

      - name: Run validate module
        run: pdk validate

      - name: Run the tests
        run: pdk test unit

      - name: Try to build the package
        run: pdk build
