# CI workflow 

name: CI

on:
    workflow_dispatch:
    pull_request:
      types: [ assigned, opened, synchronize, reopened ]
    push:
      branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install PDK
        run: |
          wget https://apt.puppet.com/puppet-tools-release-focal.deb
          sudo dpkg -i puppet-tools-release-focal.deb
          sudo apt-get update
          sudo apt-get install pdk

      - name: Run validate module
        run: pdk validate

      - name: Run the tests Puppet 4
        run: pdk test unit --puppet-version=4

      - name: Run the tests Puppet 3
        run: pdk test unit --puppet-version=3

      - name: Run the tests Puppet 5
        run: pdk test unit --puppet-version=5

      - name: Run the tests Puppet 6
        run: pdk test unit --puppet-version=6

      - name: Run the tests Puppet 7
        run: pdk test unit --puppet-version=7

      - name: Try to build the package
        run: pdk build
