# CI workflow 

name: CI

on:
    workflow_dispatch:
    pull_request:
      types: [ assigned, opened, synchronize, reopened ]
    push:
      branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install PDK
        run: |
          wget https://apt.puppet.com/puppet-tools-release-focal.deb
          sudo dpkg -i puppet-tools-release-focal.deb
          sudo apt-get update
          sudo apt-get install pdk

      - name: Run validate module
        run: pdk validate

      - name: Set placeholder token
        run: export IONOS_TOKEN=token

      - name: Run the tests Puppet 6
        run: pdk test unit --puppet-version=6
        env:
          IONOS_TOKEN: token

      - name: Run the tests Puppet 7
        run: pdk test unit --puppet-version=7
        env:
          IONOS_TOKEN: token

      - name: Try to build the package
        run: pdk build
