# Publish workflow 

name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    env:
      ruby-version: 2.7

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install PDK
        run: |
          wget https://apt.puppet.com/puppet-tools-release-focal.deb
          sudo dpkg -i puppet-tools-release-focal.deb
          sudo apt-get update
          sudo apt-get install pdk

      - name: Run validate module
        run: pdk validate

      - name: Run the tests Puppet 5
        run: pdk test unit --puppet-version=5

      - name: Run the tests Puppet 6
        run: pdk test unit --puppet-version=6

      - name: Run the tests Puppet 7
        run: pdk test unit --puppet-version=7

      - name: Try to build the package
        run: pdk build

      - name: Get the new version
        id: new_version
        run: echo ::set-output name=VERSION::$(git tag --list "v*" --sort=version:refname | tail -n 1)

      - name: Get the old version
        id: old_version
        run: echo ::set-output name=VERSION::$(git tag --list "v*" --sort=version:refname | tail -n 2 | head -n 1)

      - name: Check Version
        run: |
          if [ "${{ steps.new_version.outputs.VERSION }}" != v$(cat metadata.json | grep '"version":' | tr -s ' ' | cut -d ' ' -f 3 | cut -d '"' -f 2) ]; then
            echo "Tag version does not match the one from metadata.json!"
            exit 1
          fi

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: ${{ env.ruby-version }}

      - name: Install dependencies
        shell: bash
        run: bundle install

      - name: Install puppet-blacksmith
        shell: bash
        run: gem install puppet-blacksmith

      - name: Create Puppet Forge release of the Puppet module
        shell: bash
        run: |
          cat << EOF > ~/.puppetforge.yml
          ---
          url: https://forgeapi.puppetlabs.com
          username: ${{ secrets.PUPPETFORGE_USERNAME }}
          password: ${{ secrets.PUPPETFORGE_PASSWORD }}
          EOF
          rake module:push

      - name: Check version and create GitHub branch
        run: |
          /usr/bin/bash ./git-versioning.sh ${{ steps.new_version.outputs.VERSION }} ${{ steps.old_version.outputs.VERSION }}
